const router = require("express").Router();
const a = require("../middlewares/asincrono");
const { requiereSesion } = require("../middlewares/auth");
const subida = require("../middlewares/subida");
const c = require("../controllers/cuentaController");

router.use(requiereSesion);

router.get("/", a(c.inicio));
router.get("/reservas", a(c.reservas));
router.get("/reservas/:id", a(c.reserva));
router.get("/reservas/:id/calendario.ics", a(c.ics));
router.get("/reservas/:id/cancelar", a(c.formCancelar));
router.post("/reservas/:id/cancelar", a(c.cancelar));
router.get("/reservas/:id/reprogramar", a(c.formReprogramar));
router.post("/reservas/:id/reprogramar", a(c.reprogramar));
router.get("/reservas/:id/volver", a(c.volver));
router.post("/reservas/:id/problema", a(c.problema));
router.get("/reservas/:id/valorar", a(c.formValorar));
router.post("/reservas/:id/valorar", a(c.valorar));
router.get("/resenas", a(c.misResenas));
router.get("/resenas/:id/editar", a(c.formEditarResena));
router.post("/resenas/:id/editar", a(c.editarResena));
router.get("/favoritos", a(c.favoritos));
router.get("/mensajes", a(c.mensajes));
router.get("/mensajes/nuevo/:especialistaId", a(c.nuevoMensaje));
router.get("/mensajes/:id", a(c.conversacion));
router.post("/mensajes/:id", a(c.enviarMensaje));
router.get("/notificaciones", a(c.notificaciones));
router.post("/notificaciones/leer", a(c.leerTodas));
router.get("/notificaciones/:id", a(c.abrirNotificacion));
router.get("/perfil", a(c.perfil));
router.get("/perfil/editar", c.formEditarPerfil);
router.post("/perfil/editar", subida({ tipos: "imagen" }), a(c.editarPerfil));
router.get("/pagos", a(c.pagos));
router.get("/metodos-de-pago", c.metodosPago);
router.post("/metodos-de-pago/quitar", a(c.quitarMetodo));
router.get("/configuracion", c.configuracion);
router.post("/configuracion/avisos", a(c.guardarAvisos));
router.post("/configuracion/contrasena", a(c.cambiarClave));
router.get("/privacidad", c.privacidad);
router.post("/privacidad", a(c.guardarPrivacidad));
router.get("/privacidad/mis-datos.json", a(c.misDatos));
router.post("/privacidad/eliminar", a(c.eliminarCuenta));
router.get("/ayuda", a((req, res) => c.ayuda(req, res)));
router.post("/ayuda", a(c.crearConsulta));
router.get("/ayuda/:id", a((req, res) => c.consulta(req, res)));
router.post("/ayuda/:id", a(c.responderConsulta));

module.exports = router;
