'use strict';
// Punto único de acceso a los modelos.
module.exports = {
  User: require('./User'),
  Specialist: require('./Specialist'),
  Service: require('./Service'),
  Category: require('./Category'),
  Availability: require('./Availability'),
  Booking: require('./Booking'),
  BookingSlot: require('./BookingSlot'),
  Payment: require('./Payment'),
  Refund: require('./Refund'),
  Payout: require('./Payout'),
  CommissionRule: require('./CommissionRule'),
  Review: require('./Review'),
  Conversation: require('./Conversation'),
  Message: require('./Message'),
  Favorite: require('./Favorite'),
  Notification: require('./Notification'),
  Media: require('./Media'),
  Certification: require('./Certification'),
  VerificationRequest: require('./VerificationRequest'),
  Promotion: require('./Promotion'),
  SponsoredPlacement: require('./SponsoredPlacement'),
  AuditLog: require('./AuditLog'),
  Setting: require('./Setting'),
  Content: require('./Content'),
  Report: require('./Report'),
  Ticket: require('./Ticket'),
  StatDaily: require('./StatDaily'),
  Counter: require('./Counter'),
};
