module.exports = {
  Usuario: require("./Usuario"),
  Especialista: require("./Especialista"),
  Servicio: require("./Servicio"),
  Categoria: require("./Categoria"),
  Agenda: require("./Agenda"),
  Reserva: require("./Reserva"),
  Pago: require("./Pago"),
  Reembolso: require("./Reembolso"),
  Liquidacion: require("./Liquidacion"),
  ReglaComision: require("./ReglaComision"),
  Promocion: require("./Promocion"),
  Destacado: require("./Destacado"),
  Multimedia: require("./Multimedia"),
  Certificacion: require("./Certificacion"),
  Verificacion: require("./Verificacion"),
  Resena: require("./Resena"),
  Favorito: require("./Favorito"),
  Conversacion: require("./Conversacion"),
  Mensaje: require("./Mensaje"),
  Notificacion: require("./Notificacion"),
  Consulta: require("./Consulta"),
  Denuncia: require("./Denuncia"),
  Auditoria: require("./Auditoria"),
  Estadistica: require("./Estadistica"),
  Contenido: require("./Contenido"),
  Config: require("./Config"),
};
